services:
  camera-stream:
    build: .
    network_mode: "host"
    environment:
      - APP_PORT=${APP_PORT:-61000}
      - PUBLIC_HOST=${PUBLIC_HOST:-192.168.11.200}
    restart: unless-stopped
    tty: true
